AWSTemplateFormatVersion: 2010-09-09
Description: Create NAT Gateway

Parameters: 
  PublicSubnetId:
    Type: String


Resources: 
  EIPForNAT: #Create Elastic IP for NAT Gateway
    Type: AWS::EC2::EIP
    Properties:
      Domain: VPC
      Tags:
      - Key: Name
        Value: "Group-12-NAT-EIP"
  
  NatGateway: #Create NAT Gateway
    Type: AWS::EC2::NatGateway  
    Properties:
      AllocationId: !GetAtt EIPForNAT.AllocationId
      SubnetId: !Ref PublicSubnetId
      Tags:
        - Key: Name
          Value: "Group-12-NAT-Gateway"
Outputs:
  NatGatewayId:
    Value: !Ref NatGateway